### ISSUE TITLE
Feature request: New version of Elastic Search 6.7 support

### ISSUE THREAD

**Issue by 3dw1np** [terraform-providers/terraform-provider-alicloud#1220]
Can you support the new version 6.7 of Elastic Search for the block resource alicloud_elasticsearch_instances. It's not the case at the moment.

### Terraform Version
1.44

### Affected Resource(s)
alicloud_elasticsearch_instances

**Comment by guangfanqu** [comment]
hi Edwin,

6.7 is supported in alicloud_elasticsearch_instance.

Please assign the variable `version` value '6.7_with_X-Pack' in .tf file.

Docs is will be updated ASAP.

Thank you.

**Comment by 3dw1np** [comment]
Hi @guangfanqu thx for your reply.
Indeed it may work for a new stack but for an existing stack if we change "6.3_with_X-Pack" to "6.7_with_X-Pack".  Terraform cannot detect any changes.

"No changes. Infrastructure is up-to-date."
This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

**Comment by guangfanqu** [comment]
Hi Edwin,

Sorry to reply you later.

Aliyun Elasticsearch is not supported to upgrade or downgrade the es version.
If version is modified in .tf, terraform will destroy the old instance and create a new instance because version field is defined "ForceNew".

The bug "Terrafrom cannot detect any changes" is fixed in a new version.

If you have any problem please let me know.
thx.

**Comment by xiaozhu36** [comment]
HI  @3dw1np The release 1.47.0 has been fixed this issue. Please check it.
